stages:
  - build
  - test
  - deny
  - deploy

image: "rust:latest"

build:
  stage: build
  script:
    - cargo build --release

rustfmt:
  stage: test
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all --check
  needs: ["build"]

.install-clippy:
  before_script:
    - rustup component add clippy
  stage: test
  needs: ["build"]

lint-test-job:
  stage: test
  extends: .install-clippy
  script:
    - cargo clippy
  needs: ["build"]

include:
  project: "internal/ci-catalog"
  ref: "main"
  file: "templates/cargo_deny.yml"
  inputs:
    stage: deny

deploy:
  stage: deploy
  script:
    - cargo install cargo-shuttle
    - cargo install sqlx-cli
    - cat "$SECRETS" > Secrets.toml
    - cargo sqlx prepare
    - cargo shuttle deploy
  environment:
    name: Production
    url: https://f1-news-discord-webhook.shuttleapp.rs
    action: start
    on_stop: stop-deploy
  when: manual
  
stop-deploy:
  stage: deploy
  script:
    - cargo install cargo-shuttle
    - cargo shuttle stop
  environment:
    name: Production
    url: https://f1-news-discord-webhook.shuttleapp.rs
    action: stop
  when: manual   

