edition = "2021"
fn_args_layout = "Vertical"
fn_call_width = 80
format_code_in_doc_comments = true
imports_granularity = "crate"
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_lit_single_line = false
use_field_init_shorthand = true
use_small_heuristics = "Off"
use_try_shorthand = true
wrap_comments = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
